### ISSUE TITLE
Users Flip For Tooltip

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/temp-site#225]
These need some kind of really good tooltip

![image](https://user-images.githubusercontent.com/1503976/235469388-d66c147d-e6dc-43c5-8327-380f76c2aa98.png)

Under no circumstances should the cursor change to an i-beam and make the text selectable... except maybe that the category can have its text selected

**Comment by williln** [comment]
@gregnewman There is not a tooltip to supplement the value of the C++ minimum field (as far as I can tell) field on the model. Most of the data in the `Library` object is loaded from the `meta/libraries.json` file that each Boost library has in its repo. We do have, however, the `cpp_standard_minimum` field -- `cxxstd` in the `libraries.json`, and we have manual code for the library details page that translates the code to something more readable -- "11" to "C++11", for example. Since there are only a few values for the C++ minimum, if I'm given what the text should be, then I can just add that to the display code we already have and return it to the template that way? 

Let me know if I'm misunderstanding the problem -- for whatever reason, the screenshots are not loading for me so I'm sure I'm missing context.

**Comment by gregnewman** [comment]
We have implemented title attributes that show which version is needed.
