### ISSUE TITLE
Library Detail Backend Changes

### ISSUE THREAD

**Issue by frankwiles** [cppalliance/temp-site#252]
- [x] Gather Github stats necessary for new graphs
- [x] Render `library.adoc` in the root of the repository to HTML and save it into the database in a TextField which will be rendered below the graphs and other header/link elements.  
- [ ] Periodically pull and re-render these in a cron. Probably more frequently than we ware pulling maintainers and authors

**Comment by williln** [comment]
## Items Accomplished:

- [x] Various small data points 
- [x] Author/maintainer info 
- [x] Loaded all the versions of each library, along with their GitHub data and author/maintainer data   
- [x] Loaded the date of the first GitHub tag for all libraries 
- [x] Made the details page version-specific   

## Remaining items: 

- [ ] Render the asciidoc in the body of the details page -- @vinniefalco where do I get that content? 
- [ ] Get number of commits per month going back to when the library was added and make that available to the template 
- [ ] Make the links version-sensitive when possible (links to docs, links to github, etc.)

**Comment by vinniefalco** [comment]
> Render the asciidoc in the body of the details page -- @vinniefalco where do I get that content?

I was thinking of having it come out of a directory in the library repository. for example

```
doc/library-detail.adoc
```

or if that file is not present, then it could come from the root:

```
README.adoc
```

alternatively, we can just show nothing if "doc/library-detail.adoc" is missing, and if it is present and is also a _symbolic link_ to another file in the repo then we can resolve the link and use that file. This will allow the repository owner to create README.adoc in the root of the repository for GitHub to preview on the repository landing page, and also allow the repository owner to link doc/library-detail.adoc to README.md so that the same content appears on the corresponding library detail page.

This would have to use the right commit or branch. If the user has selected an older version then it needs to use the git tag corresponding to that version. The user can select "latest version" which is just the highest semantically valued tag. But there are also the "develop" and "master" choices which correspond to the library repository's commit-id in the superproject.

**Comment by williln** [comment]
@vinniefalco @alandefreitas Thanks for your explanations. So for the library documentation -- 

> > Render the asciidoc in the body of the details page -- @vinniefalco where do I get that content?
> 
> I was thinking of having it come out of a directory in the library repository. for example

Do the asciidoc files for the library descriptions not exist in the library repos yet? Or if they do, can you point me to the one I should be using for `asio`, just as an example? https://github.com/boostorg/asio

**Comment by vinniefalco** [comment]
The files do not exist yet :) Alan could you please copy README.md to library-detail.adoc (and convert to Asciidoc) for URL, JSON, and Beast? And ask the Boost.Redis and Boost.MySQL authors do to the same (and merge to develop)?

**Comment by alandefreitas** [comment]
@williln library-detail.adoc is in boostorg/json/doc and boostorg/url/doc. I'll still do the other libs.

**Comment by williln** [comment]
@alandefreitas Thank you! I'll use those as test cases when working on the asciidoc conversion.

**Comment by williln** [comment]
@alandefreitas @vinniefalco The code to convert and cache asciidoc content is now in place, so I'm circling back around to load the `doc/library-details.adoc` content into the body of the Library Details page for the pages that have it. 

For versions of the library that predate when that file was added or that otherwise don't have it, what should we show for the library description? 

Local example of a library with that file: 

<img width="1193" alt="Screenshot 2023-06-09 at 10 01 52 AM" src="https://github.com/cppalliance/temp-site/assets/2286304/9db12481-6155-4ab5-80b4-130853f6dc37">

And without that file: 

<img width="1104" alt="Screenshot 2023-06-09 at 10 02 29 AM" src="https://github.com/cppalliance/temp-site/assets/2286304/91bf8a7a-326f-4af5-ba44-65ebc25d627b">
