### ISSUE TITLE
explicit master and develop "versions"

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/temp-site#386]
I want to throw this out there because it seems relevant now

Users can select the "version" of Boost on the website via the version dropdown. They might select an older version such as 1.69.0 which corresponds to content in all repositories which has the tag "boost-1.69.0"

They can select "Newest Version" which is simply an alias to the most recent release, in this case it would be "boost-1.82.0"

In each case when they view the library detail page, or if they visit the library documentation, the information presented will be tied to that commit id

Since rendered documentation is not stored in the repo but generated during the release, and because we offer online access to all rendered documentation across all releases, versioned Boost library documentation is accessible with some formula that puts the version in the URL target, e.g. "https://www.boost.org/doc/libs/1_82_0/doc/html/boost_asio.html"

However it is additionally necessary to be able for the user to view "master" and "develop" documentation, or other content which is tied to the state of a library or the superproject at a specific commit-id

For example consider Boost.Beast. The "master" version of the rendered documentation is available at
http://www.boost.org/doc/libs/master/libs/beast/doc/html/index.html
while the "develop" version of the rendered documentation is available at
https://www.boost.org/doc/libs/develop/libs/beast/index.html

Since we are contemplating the Library Detail page showing rendered Asciidoc that comes from the library repository, the same principles of tying this rendered data to the commit apply

But now there's an extra wrinkle - how does the user choose the "develop" or "master" branch as the "Boost version" ?

We could put it in the version drop down...

**Comment by frankwiles** [comment]
This is totally do-able. Since header space is of particular concern, I would think we should put the version number selector (be it a dropdown or popup) in the header.  Couple of other suggestions: 

1. Rendered docs from an older version should link to the site with a query param denoting their version.  If you want to the site to honor the choice of docs in that travel direction.  So if I'm on 1_69_0 it would link back to the site with `?version=1_69_0`

2. On all "non-master" versions (old versions and develop) we should add a header banner to denote they are looking at an old version of the site.  Otherwise, it will be very easy for someone to flip the library view to old and browse around a bit and go to docs or whatever and not realize they are on old docs.  This is how we do it on the Django project: 

Latest version (master)

![CleanShot 2023-05-25 at 13 49 17](https://github.com/cppalliance/temp-site/assets/144159/295d75d8-4e9b-4235-997a-32e0d24d5d6c)

Dev version: 

![CleanShot 2023-05-25 at 13 49 49](https://github.com/cppalliance/temp-site/assets/144159/49c95858-0517-4e54-832d-6aa4139413d9)

Older version: 

![CleanShot 2023-05-25 at 13 50 15](https://github.com/cppalliance/temp-site/assets/144159/81bf333f-9e96-4a63-8d67-6fd29f857c8c)

We would use different wording of course, but you get the idea.  You only pay the "screen real estate" and "ugliness" penalty when looking at old or bleeding edge stuff.

**Comment by williln** [comment]
@vinniefalco From a data perspective, it's also not hard to add in retrieving data about the `master` and `develop` tags to the data retrieval we do from GitHub. 

For the notice, we have https://github.com/cppalliance/temp-site/issues/282 if we want to move this to that issue?

**Comment by williln** [comment]
@4down Do you know if adding `master` and `develop` as Versions to the drop-downs is something we still want to do?

**Comment by frankwiles** [comment]
Yeah we want the select box to be: 

1. current latest release
2. master
3. develop
4. second most recent release
5. third most recent release

That way master and develop are easy to get to (not at the bottom) but that they flow somewhat logically.

**Comment by williln** [comment]
Update @frankwiles @4down @sdarwin: Per PR #827, the `master` and `develop` versions can now be imported into the database by clicking the "Import New Releases" button. They will show in the drop-down on the releases page but not on the libraries page. Adding the libraries to the `master` and `develop` branches will come in a separate PR.  

![Screenshot 2023-11-15 at 8 56 06 AM](https://github.com/cppalliance/temp-site/assets/2286304/10e5d132-93b0-4a9b-9c6b-ec8ac6fdb773)
