### ISSUE TITLE
News - Creation Form Changes

### ISSUE THREAD

**Issue by frankwiles** [cppalliance/temp-site#436]
On the News List page, there should be a single button/link that takes you to creation page. 

On that creation page the user should have to choose News, Video, Link, etc. A simple single list of links/buttons to each creation form. 

Initially, only poll moderators and superusers can create polls.  Will be opened up to all users at some future date.

- [x] Interstitial page `/news/create` or something like that just to display the links/buttons to create each type
- [x] Only show poll adding option to superusers and moderators

**Comment by nessita** [comment]
@frankwiles @gregnewman Question about the intermediary page for news creation: as a user, I think that having this two stage flow is a bit cumbersome and could generate a "old site" vibe. While this may be a desired goal, I wanted to triple check if the following wouldn't be a better flow:

* From the "Submit News" link-button in the news list, take the user to a page that will have buttons for creating each type of News, but when clicked, the corresponding form is revealed instead of taking the user to yet another page.

The difference would be that all forms would be returned in the response but hidden until the user chooses a news type. Implementation wise, this is indeed a bit more involved but I'm raising it because it feels like better UX (unless we eventually do some partial template rendering in which case we could just fetch the specific news creation form on demand).

**Comment by gregnewman** [comment]
@nessita I believe (@frankwiles confirm please) that what you describe is our desired flow. We can preload the forms in that template and using alpine or htmx reveal the proper form/fields.  If we had one form with all the fields I can toggle the display of certain fields based on what button was clicked.  Happy to chat about it if you all want.

**Comment by frankwiles** [comment]
You're correct it's a better UI/UX, but that's not what is wanted.  

We want (I'm paraphrasing URLs here): 

- /news/ to be the ListView of all approved News items
- /news/add/ to be the interstitial page which is just a list of links/buttons to the individual news creation pages
- /news/add/link/ - actual Link form 
- (repeat for all news types) 

It's clunky, but it's what we're doing.

**Comment by nessita** [comment]
> You're correct it's a better UI/UX, but that's not what is wanted.
> 
> We want (I'm paraphrasing URLs here):
> 
>     * /news/ to be the ListView of all approved News items
> 
>     * /news/add/ to be the interstitial page which is just a list of links/buttons to the individual news creation pages
> 
>     * /news/add/link/ - actual Link form
> 
>     * (repeat for all news types)
> 
> 
> It's clunky, but it's what we're doing.

Thanks for the clarification! No worries, the PR I proposed is trivial to adapt to this schema. On it!
