### ISSUE TITLE
Documentation header replacement

### ISSUE THREAD

**Issue by frankwiles** [cppalliance/temp-site#534]
Moving away from the plan to inject the header into the documentation via JS. 

Plan is to: 

- [ ] Determine the various documentation forms and how to properly inject the header to them
- [ ] Cache the anonymous/non-logged in version of the docs for performance reasons (i.e. if the page gets linked on HackerNews)

**Comment by frankwiles** [comment]
@sdarwin @4down we're a bit confused on "where" in the S3 bucket the docs are.  I'm finding things linked off of the current boost.org like [this link for accumulators](https://www.boost.org/doc/libs/1_72_0/doc/html/accumulators.html) which seems to live in `site/develop/doc/html/accumulators/` and [this link for algorithm](https://www.boost.org/doc/libs/1_72_0/libs/algorithm/doc/html/index.html) which seems to live in `site/develop/libs/algorithm/doc/html/`. 

Are they just spread around sorta of messily like that and we need to create a one to one mapping per library or am I misunderstanding the situation?

**Comment by 4down** [comment]
@frankwiles I don't really know, it seems messy to me.  I wonder what is controlling the redirects - on boost.org/doc/libs, the links seem like they're nice and consistent until you click them.  ie,

the links on /doc/libs which all look nice and standardized:
https://www.boost.org/doc/libs/release/libs/accumulators/  
https://www.boost.org/doc/libs/release/libs/algorithm/
https://www.boost.org/doc/libs/release/libs/compatibility/

which redirect to:
https://www.boost.org/doc/libs/1_82_0/doc/html/accumulators.html
https://www.boost.org/doc/libs/1_82_0/libs/algorithm/doc/html/index.html
https://www.boost.org/doc/libs/1_82_0/libs/compatibility/

There's probably some underlying reason, maybe they were all eventually meant to converge on whatever the new standard was meant to be.

**Comment by frankwiles** [comment]
@vinniefalco Greg is saying at the end of our last meeting we changed our mind about doing this header injection on the old docs via Django.  And then we were going to just open the docs in a new tab for launch for now?

**Comment by sdarwin** [comment]
In a release bundle such as 1_82_0, the directory structure for library documentation starts out in `libs/` .  Most libraries are found in `libs/libraryname/`  But from there they redirect to a couple of locations:

1.  A doc/ subdirectory within that same library:

libs/unordered/index.html -> doc/html/unordered.html
libs/beast/index.html -> doc/html/index.html

2. Or, the superproject doc directory:

libs/accumulator/index.html ->   **top_level**/doc/html/accumulators.html

So, there are those two possible locations for html pages.

In the S3 bucket,  the `archives/` directory contains all the versions. 

Each of those releases follows this scheme.

**Comment by vinniefalco** [comment]
I was told that @nessita has developed a script which rewrites the generated HTML on the fly to include the header, using Beautiful Soup and without the need for special cases for all the different styles of docs. This sounds amazing :)

**Comment by nessita** [comment]
Hey @vinniefalco, I'm still working on this. There is a WIP PR linked to this bug report, and while the code is not as crazy as originally envisioned, there is an inevitably special casing for different HTML structures. There are plenty libraries that have very diverging formatting so we can't get away with handling each of those cases separately/individually.

I've been manually auditing each lib to cover for the most notorious UI issues, I'm currently at "pool" so I'm closer but there is still some more work to do.

**Comment by vinniefalco** [comment]
Oh sorry to hear that... would it be possible to create a small document (README.adoc) which explains the best practices/guidelines for what the generated html for libraries should look like in order to normalize the injection of the header? @4down

**Comment by nessita** [comment]
> Oh sorry to hear that... would it be possible to create a small document (README.adoc) which explains the best practices/guidelines for what the generated html for libraries should look like in order to normalize the injection of the header? @4down

My two cents on this: AFAIU, the work I did for this issue is relevant for those libs which docs are legacy and not migrated to asciidoc. From my conversation with @frankwiles, I believe that newer docs version written in asciidoc will be rendered properly without any need of HTML mangling.

**Comment by nessita** [comment]
Bellow I will summarize the current status of this work, and include relevant links to actual docs to either review or analyze of further steps are required.

* The legacy (original) docs can be fetched from S3 by visiting URLs such as: https://www.boost.revsys.dev/archives/1_82_0/
* The modified-on-the-fly docs (we also call them modernized docs) can be seen at an analogous URL where `/archives/` is replaced by `/docs/libs/`. So: https://www.boost.revsys.dev/docs/libs/1_82_0/
* For the sake of simplicity, I (temporarily) added a small link at the bottom of each modernized page with a shortcut to the legacy page: 
![image](https://github.com/cppalliance/temp-site/assets/124304/2bbc1137-fc26-4ebb-8ffd-c731c52e03da)

**Docs to showcase this work**
These are examples of less trivial doc pages that, IMHO, look quite decent with the modernization. The downside is that, despite dark mode works as usual, the resulting code snippets are not readable (this is caused by the legacy CSS that comes with each doc page, which varies from lib to lib).

_Follow the link at the bottom of each page to see the legacy page for comparison._
* Graphs and code snippets: https://www.boost.revsys.dev/docs/libs/1_82_0/libs/math/doc/html/math_toolkit/sf_beta/beta_function.html
* Lots of tables: https://www.boost.revsys.dev/docs/libs/1_82_0/libs/iterator/doc/html/iterator/concepts/traversal.html

**Headers that were replaced**

_Follow the link at the bottom of each page to see the legacy page for comparison._
* The simple cases:
  *  https://www.boost.revsys.dev/docs/libs/1_82_0/libs/python/doc/html/index.html
  *  https://www.boost.revsys.dev/docs/libs/1_82_0/libs/math/doc/html/index.html
  * https://www.boost.revsys.dev/docs/libs/1_82_0/tools/auto_index/doc/html/index.html
* Less simple, with a secondary nav bar
  *  https://www.boost.revsys.dev/docs/libs/1_82_0/libs/filesystem/doc/v3_design.html
  * https://www.boost.revsys.dev/docs/libs/1_82_0/libs/locale/doc/html/functions_func_c.html
  * https://www.boost.revsys.dev/docs/libs/1_82_0/libs/functional/index.html
  * https://www.boost.revsys.dev/docs/libs/1_82_0/libs/multi_array/doc/index.html

**Comment by nessita** [comment]
**Pages that may need small tweaks in style**

* The "warning" icon could use some modernization
  * https://www.boost.revsys.dev/docs/libs/1_82_0/libs/math/doc/html/math_toolkit/error_handling.html
    ![image](https://github.com/cppalliance/temp-site/assets/124304/10cf6134-0639-484e-b6ff-eee3b6f2a252)
* Table of content overflows into the main doc page
  * https://www.boost.revsys.dev/docs/libs/1_82_0/libs/predef/doc/index.html
  * https://www.boost.revsys.dev/docs/libs/1_82_0/libs/io/doc/html/io.html (this one also needs a tweak for the "last modified" black footer)

**Comment by vinniefalco** [comment]
oh hmm... this is not what I imagined at all, LOL...

for legacy docs there is no requirement to support light mode or to update the styling. In fact, those docs should look exactly the way they do now, without inheriting any style sheet. They should _only_ pick up the header and maybe the footer, but without additional style changes.

If documentation is on a white background it stays on a white background and is immune to dark mode.

**Comment by nessita** [comment]
> oh hmm... this is not what I imagined at all, LOL...
> 
> for legacy docs there is no requirement to support light mode or to update the styling. In fact, those docs should look exactly the way they do now, without inheriting any style sheet. They should _only_ pick up the header and maybe the footer, but without additional style changes.

The thing is that if they pick up the modern header, they need to include our modern CSS stylesheet that has definitions for the whole page (header, body, footer, etc). Specifically, the work I did does exactly what you say: we are using the HTML as found in S3 for a legacy doc page, and we are injecting our modern header and footer. But in order for that to look adequate, we need to include our CSS and JS files, and that may change a few things like the background color.

> If documentation is on a white background it stays on a white background and is immune to dark mode.

We could certainly disable the light/dark mode switch but WRT to keeping their original style while rendering our header appropriately, I'm not sure that's completely possible. In any case, this is something that perhaps @gregnewman can advice on more definitively.

**Comment by nessita** [comment]
For the record, the code is not making any editorial changes, their HTML DOM and `<head>` definitions remain intact. The change in the background comes from appending our CSS stylesheet which is required for our header to render appropriately. Otherwise our header looks like this:
![image](https://github.com/cppalliance/temp-site/assets/124304/23444c1e-e91d-47cd-89a8-bd982676560b)

**Comment by vinniefalco** [comment]
LOL... ewwwww!

By "editorial changes" I mean that by whatever means, we are making changes to the visual design of the original documentation.

**Comment by nessita** [comment]
> @vinniefalco Then we will need an additional tailwind style compiled _just_ for this. @nessita is pulling in our compiled styles so the header and footer display properly which affects the rest of the page. The original styles are stripped out to not have conflicts.

Adding to this, even if we have a dedicated tailwind style for an "isolated header", we'd have to make further adjustment for the header to not overlap into their content. This means: given our header "flows" above the page body, if we "just" add our header but not some other surrounding definitions, we get things like this:
![image](https://github.com/cppalliance/temp-site/assets/124304/2b309b2a-5b85-4fc8-9a7d-d2b3e05d3b5c)

As you can see, the page `<h1>` is hidden behind our header (because our header is meant to flow at the top at all times).

**Comment by nessita** [comment]
For completeness sake, below a link to a doc page which is very troublesome since AFAIU the page content is fetched after page load via JS (so it's impossible to mangle the HTML to insert our header before returning the page to the client):
* https://www.boost.revsys.dev/docs/libs/boost_1_61_0/libs/gil/doc/index.html

Legacy at:
* https://www.boost.revsys.dev/archives/boost_1_61_0/libs/gil/doc/index.html

**Comment by vinniefalco** [comment]
> https://www.boost.revsys.dev/docs/libs/boost_1_61_0/libs/gil/doc/index.html

oh lordy... how does GIL documentation work without Internet ?

**Comment by frankwiles** [comment]
@vinniefalco not sure what you mean by "without internet", the same as it would have been before.

**Comment by vinniefalco** [comment]
I'm talking about before. You said GIL fetches the page content using Javascript, how does that work when there's no server (i.e. the docs are bundled as static HTML in the release archive)?
