### ISSUE TITLE
Redis database deployment

### ISSUE THREAD

**Issue by sdarwin** [cppalliance/temp-site#647]
Currently `redis` is running in k8s `kind: Deployment` with 1 replica.  Stage and production namespaces. 

Observing what happens when temp-site code is updated and rolled out, GKE will launch new pods and re-arrange pods on the nodes. This causes the redis master instance to be restarted.  The redis memory store will be deleted and start from scratch each time this occurs.

A solution to the problem, which I am tending towards implementing, is moving redis from being a k8s deployment,  to instead being a hosted redis Memorystore instance https://cloud.google.com/memorystore 

@frankwiles, questions:  

- How sensitive is the current configuration to the case where redis is restarted and loses all data?
- Same question about celery?  (Or, if celery stores data in redis, then celery itself can be rebooted any time)
- What tasks is redis handling?  Including in the foreseeable future.  
- Do you agree the added stability of a hosted redis instance that never loses data will be worthwhile?

**Comment by frankwiles** [comment]
Redis shouldn't get updated and rolled as part of a `helm upgrade`.  On our cluster ours has been running for 18 days across maybe deploys (only restarted due to a node failure).  In our case it's also based by a persistent volume so data isn't lost. 

But to answer your questions: 

1. Rebooting redis and losing it's data would remove all Celery tasks that are yet to be processed (and the results if they are stored which we don't normally do) 
2. Celery keeps all of it's data in Redis about which tasks are in flight, which need to be done, reprocessed, etc. so you can restart Celery at will without issue
3. @williln alerted me to the fact that we haven't been running Celery on the REVSYS site, which is my mistake, but it's used for things like refreshing content from S3, updating library data, grabbing updated github photos, etc.  It is also used for caching data in a key/value style. 
4. I think it's fine to use the GCP hosted Redis if you find that easier, I tend to just use the bitnami Redis chart and turn on persistence and just have it run in cluster myself. 

It's definitely worth having persistence in one way or another long term!

**Comment by sdarwin** [comment]
> Redis shouldn't get updated and rolled as part of a helm upgrade. 

It shouldn't, however after a code deploy GKE decides to solve a ["bin packing problem"](https://en.wikipedia.org/wiki/Bin_packing_problem) and rearranges the pods on different nodes, causing a restart.    

> based by a persistent volume so data isn't lost.  

Yes a persistent volume would be a solution.

**Comment by frankwiles** [comment]
If you're seeing Redis kick over every time you run `helm upgrade` then something is wrong.  You're correct in that GKE (and K8S in general) does pack pods based on requests and limits (which we don't have set by the way in the helm chart) but it only does that when a pod is scheduled, not when ANY pod is scheduled.  

So if Redis is getting restarted on you frequently something else is up.

**Comment by sdarwin** [comment]
>  something else is up.

Well, keep in mind this is GKE Autopilot. (which they recommended).
With Autopilot you don't manage the nodes.  
In a small cluster, their energetic packing of pods goes so far as to launch new nodes, exactly matching requirements. Move the pods over, and shut down the earlier nodes.   At the moment, three nodes have uptimes of 1, 5, and 6 days. So they were recently launched.

**Comment by sdarwin** [comment]
Resolved by https://github.com/cppalliance/temp-site/pull/650

Created GCP Memorystore instances.  Production is using "Standard" HA, 1GB cache. Stage has a "Basic", 1GB redis instance.
