### ISSUE TITLE
Create a Post for Video Bug

### ISSUE THREAD

**Issue by louistatta** [cppalliance/temp-site#773]
![Uploading 500.jpg…]()

**Comment by louistatta** [comment]
Blogs, Polls, Videos returning Server 500 error when you try to create one

**Comment by frankwiles** [comment]
@sdarwin are there any associated logs related to this maybe that could help us debug it?

**Comment by sdarwin** [comment]
I have tested creating blog posts and links at https://www.preview.boost.org/news/add/ .   This works, as an admin user, and a standard user.

There are currently "news" and "links" on the site.  How were they added? Did you get errors, but it still went through?

Which URLs were followed, at each step? Does this URL cause an error? https://www.preview.boost.org/news/add/link/

In GCP Cloud Logging I ran a query as follows:

resource.labels.namespace_name="production" AND textPayload:"/link/"

It did not bring up errors, just info messages.

**Comment by 4down** [comment]
@sdarwin I'm getting a 500 also.

I have a feeling this would be causing it:

```
------WebKitFormBoundaryeH2DbIO4RUzhI65C
Content-Disposition: form-data; name="image"; filename=""
Content-Type: application/octet-stream


------WebKitFormBoundaryeH2DbIO4RUzhI65C
Content-Disposition: form-data; name="update"


------WebKitFormBoundaryeH2DbIO4RUzhI65C--
```

**Comment by sdarwin** [comment]
In the logs:

```
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(50)
```

Many hyperlinks, Titles, or Descriptions could be longer than 50 characters. 

Checking the format of the database table:

```
\d news_entry;
                                     Table "public.news_entry"
    Column    |           Type           | Collation | Nullable |             Default              
--------------+--------------------------+-----------+----------+----------------------------------
 id           | bigint                   |           | not null | generated by default as identity
 slug         | character varying(50)    |           | not null | 
 title        | character varying(255)   |           | not null | 
 content      | text                     |           | not null | 
 external_url | character varying(200)   |           | not null | 
 image        | character varying(100)   |           |          | 
 created_at   | timestamp with time zone |           | not null | 
 publish_at   | timestamp with time zone |           | not null | 
 author_id    | integer                  |           | not null | 
 approved_at  | timestamp with time zone |           |          | 
 moderator_id | integer                  |           |          | 
 modified_at  | timestamp with time zone |           | not null | 
```

An external URL may be 200 characters, so that limit wasn't reached.

The "slug" is limited to 50 characters.  

The "slug" is being formed from the Title:

```
15 | peter-turcan-documentation-status             | Peter Turcan Documentation Status               | 
```

Probably

1. The slug should be allowed to be somewhat larger such as 100 char.  
2. When generating that field, truncate it before it reaches the limit.

**Comment by 4down** [comment]
@frankwiles 

`django.db.utils.DataError: value too long for type character varying(50)`

This error comes up in the logs when I try to post a link.

Looks like it is this:
https://stackoverflow.com/questions/9036102/databaseerror-value-too-long-for-type-character-varying100

Top answer:
![image](https://github.com/cppalliance/temp-site/assets/49487079/2f0f00a4-1720-4098-9497-f5ec952f07d8)

![image](https://github.com/cppalliance/temp-site/assets/49487079/2cf25762-62b4-4b46-895c-609ae219d458)

Looks like max length isn't set for slug anywhere, while it is being explicitly set for the field from which the slug is derived.

**Comment by 4down** [comment]
What @sdarwin said.

**Comment by 4down** [comment]
Though, truncating the slug could create problems?  I believe the slug would always be the same length or less since non-alphanumeric characters are removed - but, I don't know exactly how it's being created here or if we have any that use a combination of fields.  

example where it could be a problem to truncate though:

Building Momentum: Spencer's Boost Website Improvements Part 1
Building Momentum: Spencer's Boost Website Improvements Part 2

**Comment by sdarwin** [comment]
> could be a problem to truncate though:

that is true
