### ISSUE TITLE
"All News" to close to other text

### ISSUE THREAD

**Issue by louistatta** [cppalliance/temp-site#798]
![image](https://github.com/cppalliance/temp-site/assets/1509548/7a8e2965-b400-4a3e-876c-19f59097694a)

**Comment by 4down** [comment]
![image](https://github.com/cppalliance/temp-site/assets/49487079/9bede202-4ac4-42e5-afbe-94b1905de225)

Makes sense to do away with the 2 column approach since the site has the fixed width.  Also the Library Spotlight column will always be the same height as the news column too which leaves a lot of blank space now with actual news in there.

I'll handle this.
