### ISSUE TITLE
Doc caching not working or not aggressive enough 

### ISSUE THREAD

**Issue by frankwiles** [cppalliance/temp-site#835]
- Can take up to several seconds to load a document

Either Redis caching isn't enabled or something else is up.

**Comment by sdarwin** [comment]
- The size of the hosted google redis cache is currently 1GB.  Pretty small.  After telnetting, I don't see webpages there. 
- What is happening though, the website is caching in the postgres database `core_renderedcontent` table.  OK.  The pages are cached.
- In that table, the `last_updated_at` field is not set.   No timestamp fields are set.    How will it purge content after an hour, a day, a week, without timestamps?
- Fixing django caching is moderately helpful, yes, but ultimately the goal can be to work on getting the front-end CDN cache be the main performance booster.

**Comment by sdarwin** [comment]
Fastly has been added to stage.boost.cppalliance.org. The slow webpage unordered.html takes 1 second through the CDN.  It's fast.

This solves 90% of the problems. Backend servers are shielded and it improves performance.

going to the next topic, the 10% of users who are authenticated have a session token and don't use the cache. They will be slower.  Here's another proposal to fix that.  The only thing which is customized on /doc/ pages is the profile photo. So,

1. Set a cookie with the exact name of the profile photo.
2. Load the profile photo using javascript based on that cookie setting.

With that in place, it's one step closer to a scenario where the html won't vary from user to user. If the html content is 100% the same, we can configure Fastly to cache /doc/ pages regardless of authenticated status.

A problem with Django caching, and why to avoid it: if one version of boost is nearly 1GB, and there could eventually be 100 versions of boost, that's up to 100GB in total.  Web crawlers will eventually hit all pages.   Causing
all pages to eventually go into the cache. Up to 100GB added in the postgres database. Unless that is frequently emptied. 

Instead, it would be easier to allow the fastly frontend CDN to handle all caching.  Disable django-side caching.

**Comment by williln** [comment]
A small contribution to the conversation: 

> In [the rendered content] table, the last_updated_at field is not set. No timestamp fields are set. How will it purge content after an hour, a day, a week, without timestamps? 

This table also holds the release notes for older releases, which we don't want to purge from the database since they don't change. Those will have a cache key with this format: `release_notes_*`. Let me know if it would be easier to store the release notes on their own table.

**Comment by sdarwin** [comment]
In an earlier comment, I mentioned that it appears we are on track in the near future for the database to fill up with 50GB to 100GB of boost documentation, because the cache table caches all pages. Date fields were not populated.

Since then, the CDN has been set up. We can adjust the cache timeout of boost documentation in Fastly to be very long. Most pages should yield a cache hit.

Therefore, I think, disable django-side caching.  If somehow you still believe django caching should be enabled, please add documentation in docs/ explaining exactly how that works: when the purging decision is made, based on what criterion, what the maximum size of the db table is.    But I think database backups and server maintenance will be easier, if there aren't 100GB of extra docs stored in the database.  The CDN is already taking care of that.

**Comment by williln** [comment]
@sdarwin #879 should address this issue: the rendered content in the database will now purge every 7 days, and the command to do that will run nightly. Docs have also been added. If 7 days is still too much data, the docs now cover a setting where you can change the number of days to hold content before it's purged. Let me know what else you need!

**Comment by sdarwin** [comment]
@williln  thanks.   We will can try it out, and see how it goes. Maybe it will be fine.  I continue to think, that if a web crawler hits the website, loads all documentation into the cache, not just boost 1.84.0, but also boost 1.40.0 etc.   And then for 7 days that will be the size of the database.     Not necessarily critical.
