### ISSUE TITLE
Refresh of "Commits per Month" 

### ISSUE THREAD

**Issue by sdarwin** [cppalliance/temp-site#926]
It's an open question how often "Commits per Month" should update, maybe once per week is enough.       No need to overload the github api.      However it seems like that is not updating at all?      https://www.preview.boost.org/libraries/url/boost-1-84-0/

**Comment by williln** [comment]
@sdarwin I added a button to the Admin under "Commit Data" that will allow you to update the commit data ad hoc, and I ran it in staging. It seems to have worked! https://www.stage.boost.cppalliance.org/libraries/url/boost-1-84-0/ 

The button is **Update Commit Data** and it's in the upper right corner of this page: https://www.stage.boost.cppalliance.org/admin/libraries/commitdata/

**Comment by sdarwin** [comment]
@williln in production I have not clicked "Update Commit Data" to see if the scheduled updates will run.   
https://www.preview.boost.org/libraries/unordered/boost-1-84-0/   Not yet refreshed.  That's ok. Does it need more time?

**Comment by williln** [comment]
@sdarwin I set up the schedule so that the current month is refreshed every day, and the prior 12 months is only retrieved on the first of the month. I think the nightly refresh is working because I can see commit data from the current month in the admin: 

https://www.preview.boost.org/admin/libraries/commitdata/?o=-3 

But there is a gap in data between January 2024 and August 2023, so the monthly update hasn't run because it hasn't hit the first of the month. I can change the 12 month refresh schedule to something easier to test, maybe set it to every Saturday?

**Comment by sdarwin** [comment]
No it's fine, the longer schedules are better.    I have just clicked Update Commit Data, let's see.
