### ISSUE TITLE
Boost Software License page not available

### ISSUE THREAD

**Issue by Lastique** [cppalliance/temp-site#968]
The http://www.boost.org/LICENSE_1_0.txt URL, as well as its https equivalent, is typically used in copyright notices. This URL leads to the actual Boost Software License document on the old website, but this page is not present on the new website.

The license URL should be reachable on the new website, both through HTTP and HTTPS.

BSL should also be reachable via normal navigation on the website.

**Comment by sdarwin** [comment]
@4down there is a file https://github.com/cppalliance/temp-site/blob/master/static/license.txt hosted at https://www.preview.boost.org/static/license.txt .  To be more consistent with the previous boost site, can it be renamed to LICENSE_1_0.txt, and add a route at the top level / dir (instead of /static/)

**Comment by 4down** [comment]
This is about to be merged.  I did this via Django URL routing, if this seems like a concern, we may want to move it up a level to the web server.  But since it's a one-to-one route and not dynamic, there shouldn't be a concern.
